image:
  registry: docker.io
  repository: bitnami/jenkins
  tag: 2.277.1-debian-10-r2
  pullPolicy: IfNotPresent
  pullSecrets: []

kubeVersion:
hostAliases: []
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
jenkinsUser: user
jenkinsHome: /opt/bitnami/jenkins/jenkins_home

disableInitialization: "no"
javaOpts: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
command: []
args: []
extraEnvVars: []
extraEnvVarsCM:
extraEnvVarsSecret:
containerPorts:
  http: 8080
  https: 8443
podSecurityContext:
  enabled: true
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
resources:
  limits: {}
     cpu: 500m
     memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /login
    port: http
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: true
  httpGet:
    path: /login
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

customLivenessProbe: {}
customReadinessProbe: {}
updateStrategy:
  type: RollingUpdate

podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []

affinity: {}
nodeSelector: {}
tolerations: []
persistence:
  enabled: true
  annotations:
  ## Persistent Volume Access Mode
  ##
  accessModes:
  size: 8Gi

service:
  type: ClusterIp
  port: 80
  httpsPort: 443
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}

ingress:
  enabled: false
  certManager: false
  pathType: ImplementationSpecific
  apiVersion:
  hostname: jenkins.local
  path: /
  annotations: {}
  tls: false
  secrets: []

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
    pullSecrets: []

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/jenkins-exporter
    tag: 0.20171225.0-debian-10-r399
    pullPolicy: IfNotPresent
    pullSecrets: []

  podAnnotations: {}
  resources:
    limits: {}
    requests: {}

  service:
    type: ClusterIP
    ##
    port: 9122
    nodePort: ""
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"

  serviceMonitor:
    enabled: false
    selector: {}