mongodb:
  fullnameOverride: mongodb-stage
  image:
    repository: bitnami/mongodb
    tag: 4.2.8-debian-10-r24
auth:
  rootPassword: 123456789
strategyType: Recreate
tolerations:
  - operator: Exists
    effect: NoExecute
  - operator: Exists
    effect: NoSchedule
resources:
  limits:
    cpu: 200m
    memory: 1536Mi
  requests:
    cpu: 150m
    memory: 1536Mi
extraFlags:
  - "--wiredTigerCacheSizeGB=0.25"
externalAccess:
  enabled: true
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
pdb:
  create: true
  minAvailable: 1

persistence:
  enabled: true
  mountPath: /bitnami/mongodb
  subPath: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

arbiter:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 96Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mongodb-exporter
    tag: 0.11.2-debian-10-r79
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
