apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  labels:
    type: local
spec:
  storageClassName: mongo-db-persistence
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8s/data"
